# -*- coding: utf-8 -*-
"""Qr Code creator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fp60fx_2nmK_VshiUSPZALPG7zgrvjiu
"""

!pip install qrcode

import qrcode
import os

def generate_qr(data, filename, fill_color='#a9a9a9', back_color='white', box_size=10, border=2):
    """
    Generates a QR image file with the given data and configurations.

    Parameters:
        data (str): The text or link to encode.
        filename (str): The file name to save the image (e.g., 'my_qr.png').
        fill_color (str): The color of the QR code.
        back_color (str): The background color.
        box_size (int): The size of each "box" in the QR.
        border (int): The border thickness.
    """

    # 1. Validate that data is provided
    if not data.strip():
        print("Error: No data provided. Cannot generate an empty QR code.")
        return

    # 2. Configure the QR object
    #    Added 'error_correction' to make it more robust.
    #    'ERROR_CORRECT_M' allows the QR to be readable even if ~15% is damaged.
    qr = qrcode.QRCode(
        version=1,  # Starts at 1; 'fit=True' will adjust if necessary
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=box_size,
        border=border,
    )

    qr.add_data(data)
    qr.make(fit=True)  # 'fit=True' ensures the size adjusts to the data

    # 3. Create the image
    img = qr.make_image(fill_color=fill_color, back_color=back_color)

    # 4. Save the image with error handling
    try:
        img.save(filename)
        # User feedback
        print(f"\nSuccess! Your QR code has been saved as: '{filename}'")
        print(f"Location: {os.path.abspath(filename)}")  # Shows full path

    except Exception as e:
        print(f"Error: Could not save the file. Reason: {e}")

def main():
    """
    Main function that handles user interaction.
    """
    print("--- Professional QR Code Generator ---")

    # Ask the user for data
    data = input("Enter the link or text to encode: ")

    # Ask for a file name
    filename = input("What do you want to name the file? (e.g., my_qr.png): ")

    # 5. Validate user input
    if not filename.strip():
        filename = "generated_qr.png"  # Default value
        print(f"No name specified. Using default name '{filename}'.")

    # Ensure it ends with a valid image extension
    if not filename.lower().endswith(('.png', '.jpg', '.jpeg')):
        filename += '.png'
        print(f"Adding .png extension. Final name: '{filename}'")

    # Use your original example colors
    fill_original = 'black'
    back_original = 'white'

    # Call the reusable function
    generate_qr(data, filename, fill_color=fill_original, back_color=back_original)

main()